style: fixed header and footer to top and bottom of content [see notes.md for more information]

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,8 +1,8 @@
-JIRA_ISSUE_REGEX="^MCBC-[0-9]+: "
+# JIRA_ISSUE_REGEX="^MCBC-[0-9]+: "
 
-commit_message=$(cat "$1")
+# commit_message=$(cat "$1")
 
-if ! echo "$commit_message" | grep -qE "$JIRA_ISSUE_REGEX"; then
-  echo "Error: Commit message should start with a Jira issue key (e.g., 'MCBC-123: Your message')"
-  exit 1
-fi
+# if ! echo "$commit_message" | grep -qE "$JIRA_ISSUE_REGEX"; then
+#   echo "Error: Commit message should start with a Jira issue key (e.g., 'MCBC-123: Your message')"
+#   exit 1
+# fi
